name: release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.16.0"
      - name: Build AMD64 workflow
        run: |
          make ARCH=amd64
          make ARCH=arm64
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pass_rank_amd64.alfredworkflow
            pass_rank_arm64.alfredworkflow
