name: release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.16.0"
      - name: Import Apple certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERT_DATA }}
          p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}
      - name: Build universal pass_rank binary
        run: make pass_rank/pass_rank
      - name: Sign pass_rank binary
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: codesign -s "$APPLE_TEAM_ID" --timestamp --options runtime pass_rank/pass_rank
      - name: Build the workflow
        run: make
      - name: Store notarize credentials
        env:
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: xcrun notarytool store-credentials "notarytool-profile" --apple-id "$AC_USERNAME" --team-id "$APPLE_TEAM_ID" --password "$AC_PASSWORD"
      - name: Notarize the workflow
        run: xcrun notarytool submit pass.alfredworkflow --keychain-profile "notarytool-profile" --wait
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pass.alfredworkflow
